from langchain_community.document_loaders import TextLoader
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings

loader1 = TextLoader("data/file1.txt")
loader2 = TextLoader("data/file2.txt")
loader3 = TextLoader("data/RAG.txt")

docs = loader1.load() + loader2.load() + loader3.load() 

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db = Chroma.from_documents(docs, embeddings)

retriever = db.as_retriever()

print(retriever.invoke("tell me about the content of the documents?"))

#Are they stored in the chroma database? 
# Yes, they are stored in the chroma database.

#How are they indexed in the chroma database?
# They are indexed in the chroma database using the embeddings generated by the HuggingFaceEmbeddings model. 
# Each document is transformed into a vector representation, which allows for efficient retrieval based on semantic similarity.

#Do they use keys and values in the chroma database?
# Yes, the chroma database uses keys and values to store the documents. 
# The keys are the vector representations of the documents, and the values are the actual document contents.

#How do you retrieve the documents from the chroma database?
# You can retrieve the documents from the chroma database using the retriever.
# The retriever allows you to query the database with a natural language question, and it will

#Which method is used to retrieve the documents from the chroma database?
# The method used to retrieve the documents from the chroma database is the `invoke` method of the retriever.

#Which method is used to store the documents in the chroma database?
# The method used to store the documents in the chroma database is the `from_documents` method of the Chroma class.

